baseURL = "https://test.davylandman.nl/"
languageCode = "en-us"
title = "Davy Landman"
author = "Davy Landman"
theme = "own-style"

[params]
    dateformat = "2 Jan 2006"

[params.meta]
    description = "Davy Landman's personal homepage"
    keywords = "personal,blog,about,developer,phd"

